version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
# myaosato (me)
  - arrp
  - clcm
  - myao_s_moking
  - myaosato
  # books
  - alfanote
  - kadokawa
  # common lisp
  - clhs
  - defpackage
  - defun
  - expt
  - sbcl
  - setf
  - sicp
  # software
  - wireshark
  # music
  - bridear
  - rolly
  # programming
  - fuga
  - hoge
  - piyo
  # video game
  - skyrim
import: []
