version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
- arrp
- clcm
- clhs
- defpackage
- defun
- expt
- fuga
- hoge
- myaosato
- piyo
- sbcl
- setf
- sicp
- skyrim
ignoreWords: []
import: []
